### ISSUE TITLE
Getting manifest merger error

### ISSUE THREAD

**Issue by satnamvision** [Turtlebody/android-media-picker#4]
Attribute provider#androidx.core.content.FileProvider@authorities value=(my_package_name) from AndroidManifest.xml:41:13-60 is also present at AndroidManifest.xml:22:13-86 value=(my_package_name.greentoad.turtlebody.mediaprovider). Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:39:9-47:20 to override. app main manifest (this file), line 40

**Comment by wangsun6** [comment]
The merging is getting failed because of present of 2 FileProvider with same name 'androidx.core.content.FileProvider'


If you want a quick fix, just create a class that extends FileProvider such as:

`
public class MyFileProvider extends FileProvider {
}
`
and in your manifest file you change it to:

`
<provider android:name=".MyFileProvider" 
... >
`
